name: CI - Gradle Build
# Event
on:
  pull_request:
    branches: [ develop ]

# 권한 설정
permissions:
  contents: read

# Work
jobs:
  build:
    runs-on: ubuntu-latest # 실행 환경
    steps:
      - uses: actions/checkout@v3 # 기본 체크아웃 동작
      # Java version 세팅
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      # 환경 변수 설정
      - name: Set up Environment
        run: echo "${{ secrets.ENV_PROPERTIES }}" > ./.env # GitHub SecretKey 에서 설정한 내용으로 .env 파일 생성

      # 테스트를 진행하기 위해 액션 서버에 docker로 mysql 띄우기
      - name: Create mysql docker container
        run: sudo docker run -d -p 3305:3306 --env MYSQL_DATABASE="${{ secrets.TEST_DATABASE }}" --env MYSQL_ROOT_PASSWORD="${{ secrets.TEST_DATASOURCE_PASSWORD }}" mysql:8.0.31

      # 빌드시 캐시 적용
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle
      # 빌드
      - name: Build with Gradle
        run: ./gradlew build